import type { FoodItem, QuizQuestion } from "../types";

export const PERSON_DAILY_LITERS = 110;
export const SITE_NAME = "Água Invisível";
export const SITE_URL = "https://agua-invisivel.vercel.app";

export const WATER_CONSUMPTION = {
  clothing: {
    jeans: 5196,
    tshirt: 2700,
  },
  food: {
    rice_1kg: 1700,
    coffee_cup: 840,
    beef_1kg: 15000,
    pork_1kg: 6000,
    milk_1l: 1000,
    tomato: 13,
  },
  ai: {
    chatgpt_command: { min: 0.01, max: 0.05 },
  },
  comparisons: {
    jeans_daily_water_for_people: 47,
    loss_percentage_brazil: 37,
    people_without_water_br: 32_000_000,
  },
} as const;

export const FOOD_CATALOG: FoodItem[] = [
  {
    id: "rice",
    slug: "arroz",
    name: "Arroz",
    category: "graos",
    quantity: 1,
    unit: "kg",
    waterUsed: 1700,
    icon: "/images/food/rice.svg",
    description: "Um quilo de arroz irriga cerca de 1.700 litros ao longo do cultivo.",
  },
  {
    id: "coffee",
    slug: "cafe",
    name: "Café",
    category: "bebidas",
    quantity: 1,
    unit: "xícara",
    waterUsed: 840,
    icon: "/images/food/coffee.svg",
    description: "Do grão à xícara, o café concentra uma das maiores pegadas entre as bebidas.",
  },
  {
    id: "beef",
    slug: "carne-bovina",
    name: "Carne bovina",
    category: "carnes",
    quantity: 1,
    unit: "kg",
    waterUsed: 15000,
    icon: "/images/food/beef.svg",
    description: "Ração, pastagem e dessedentação elevam a pegada da carne bovina.",
  },
  {
    id: "pork",
    slug: "carne-suina",
    name: "Carne suína",
    category: "carnes",
    quantity: 1,
    unit: "kg",
    waterUsed: 6000,
    icon: "/images/food/pork.svg",
    description: "Ainda alta, mas bem menor do que a da carne bovina.",
  },
  {
    id: "chicken",
    slug: "frango",
    name: "Frango",
    category: "carnes",
    quantity: 1,
    unit: "kg",
    waterUsed: 4300,
    icon: "/images/food/chicken.svg",
    description: "Alternativa com pegada intermediária entre carne vermelha e vegetais.",
  },
  {
    id: "milk",
    slug: "leite",
    name: "Leite",
    category: "laticinios",
    quantity: 1,
    unit: "litro",
    waterUsed: 1000,
    icon: "/images/food/milk.svg",
    description: "Produzir um litro de leite exige cerca de mil litros de água virtual.",
  },
  {
    id: "cheese",
    slug: "queijo",
    name: "Queijo",
    category: "laticinios",
    quantity: 1,
    unit: "kg",
    waterUsed: 5000,
    icon: "/images/food/cheese.svg",
    description: "A concentração do leite no queijo multiplica a pegada hídrica.",
  },
  {
    id: "tomato",
    slug: "tomate",
    name: "Tomate",
    category: "legumes",
    quantity: 1,
    unit: "unidade",
    waterUsed: 13,
    icon: "/images/food/tomato.svg",
    description: "Um tomate médio consome cerca de 13 litros no campo.",
  },
  {
    id: "lettuce",
    slug: "alface",
    name: "Alface",
    category: "legumes",
    quantity: 1,
    unit: "pé",
    waterUsed: 14,
    icon: "/images/food/lettuce.svg",
    description: "Folhosos têm pegada baixa quando comparados a proteínas animais.",
  },
  {
    id: "carrot",
    slug: "cenoura",
    name: "Cenoura",
    category: "legumes",
    quantity: 1,
    unit: "unidade",
    waterUsed: 33,
    icon: "/images/food/carrot.svg",
    description: "Raízes em geral são uma escolha de baixo consumo hídrico.",
  },
  {
    id: "potato",
    slug: "batata",
    name: "Batata",
    category: "legumes",
    quantity: 1,
    unit: "kg",
    waterUsed: 290,
    icon: "/images/food/potato.svg",
    description: "Um quilo de batata usa menos de 300 litros — contraste forte com carnes.",
  },
  {
    id: "beans",
    slug: "feijao",
    name: "Feijão",
    category: "graos",
    quantity: 1,
    unit: "kg",
    waterUsed: 4000,
    icon: "/images/food/beans.svg",
    description: "Proteína vegetal com pegada menor do que a da carne, mas ainda relevante.",
  },
  {
    id: "bread",
    slug: "pao",
    name: "Pão",
    category: "graos",
    quantity: 1,
    unit: "kg",
    waterUsed: 1600,
    icon: "/images/food/bread.svg",
    description: "Trigo, fermentação e processamento somam cerca de 1.600 litros por quilo.",
  },
  {
    id: "apple",
    slug: "maca",
    name: "Maçã",
    category: "frutas",
    quantity: 1,
    unit: "unidade",
    waterUsed: 70,
    icon: "/images/food/apple.svg",
    description: "Uma maçã média representa cerca de 70 litros de água virtual.",
  },
  {
    id: "banana",
    slug: "banana",
    name: "Banana",
    category: "frutas",
    quantity: 1,
    unit: "unidade",
    waterUsed: 160,
    icon: "/images/food/banana.svg",
    description: "Fruta comum no Brasil, com pegada moderada por unidade.",
  },
  {
    id: "orange",
    slug: "laranja",
    name: "Laranja",
    category: "frutas",
    quantity: 1,
    unit: "unidade",
    waterUsed: 50,
    icon: "/images/food/orange.svg",
    description: "Uma laranja usa cerca de 50 litros — bem menos que um suco industrializado em larga escala.",
  },
  {
    id: "egg",
    slug: "ovo",
    name: "Ovo",
    category: "outros",
    quantity: 1,
    unit: "unidade",
    waterUsed: 200,
    icon: "/images/food/egg.svg",
    description: "Cada ovo carrega cerca de 200 litros da cadeia de produção.",
  },
  {
    id: "chocolate",
    slug: "chocolate",
    name: "Chocolate",
    category: "outros",
    quantity: 1,
    unit: "kg",
    waterUsed: 17000,
    icon: "/images/food/chocolate.svg",
    description: "Cacau é uma das culturas com maior pegada hídrica por quilo.",
  },
  {
    id: "beer",
    slug: "cerveja",
    name: "Cerveja",
    category: "bebidas",
    quantity: 1,
    unit: "litro",
    waterUsed: 300,
    icon: "/images/food/beer.svg",
    description: "Cevada, lúpulo e o próprio processo industrial pesam na conta.",
  },
  {
    id: "sugar",
    slug: "acucar",
    name: "Açúcar",
    category: "outros",
    quantity: 1,
    unit: "kg",
    waterUsed: 1500,
    icon: "/images/food/sugar.svg",
    description: "A cana é irrigada em várias regiões — 1 kg de açúcar ≈ 1.500 litros.",
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  legumes: "Legumes",
  carnes: "Carnes",
  bebidas: "Bebidas",
  frutas: "Frutas",
  graos: "Grãos",
  laticinios: "Laticínios",
  outros: "Outros",
};

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: "q1",
    question: "Quantos litros de água são necessários para produzir uma calça jeans?",
    options: ["480 litros", "1.200 litros", "5.196 litros", "12.000 litros"],
    answer: 2,
    insight: "Do algodão ao tingimento, um jeans médio consome 5.196 litros — água para 47 pessoas por um dia.",
    litersSaved: 5196,
  },
  {
    id: "q2",
    question: "Qual destes alimentos tem a maior pegada hídrica por quilo?",
    options: ["Arroz", "Frango", "Carne bovina", "Batata"],
    answer: 2,
    insight: "A carne bovina chega a 15.000 litros por quilo. Trocar uma porção já muda o quadro do mês.",
    litersSaved: 1800,
  },
  {
    id: "q3",
    question: "Cerca de quantos litros uma xícara de café “esconde”?",
    options: ["12 litros", "84 litros", "840 litros", "8.400 litros"],
    answer: 2,
    insight: "O café é um dos vilões silenciosos do café da manhã: 840 litros por xícara.",
    litersSaved: 840,
  },
  {
    id: "q4",
    question: "Qual é a estimativa de perda de água tratada na distribuição no Brasil?",
    options: ["12%", "21%", "37%", "54%"],
    answer: 2,
    insight: "37% da água tratada se perde em vazamentos e ligações irregulares — o suficiente para abastecer milhões.",
    litersSaved: 110,
  },
  {
    id: "q5",
    question: "Um comando de IA (como o ChatGPT) consome água?",
    options: [
      "Não, é só eletricidade",
      "Sim, data centers usam água para resfriar servidores",
      "Apenas se o prompt for longo",
      "Somente em treino de modelos, nunca em uso",
    ],
    answer: 1,
    insight: "Estimativas educacionais apontam 0,01 a 0,05 L por comando, por causa do resfriamento dos data centers.",
    litersSaved: 1,
  },
  {
    id: "q6",
    question: "Quantos brasileiros vivem sem acesso adequado à água, segundo o recorte deste projeto?",
    options: ["3,2 milhões", "12 milhões", "32 milhões", "87 milhões"],
    answer: 2,
    insight: "Enquanto 32 milhões seguem sem água adequada, 37% da água tratada ainda se perde na rede.",
    litersSaved: 110,
  },
  {
    id: "q7",
    question: "Quantos litros para 1 kg de arroz?",
    options: ["170 litros", "1.700 litros", "7.000 litros", "15.000 litros"],
    answer: 1,
    insight: "O arroz irriga bastante, mas ainda assim consome cerca de 9 vezes menos água que a carne bovina por quilo.",
    litersSaved: 255,
  },
  {
    id: "q8",
    question: "Uma camiseta de algodão equivale a quantos litros, em média?",
    options: ["270 litros", "2.700 litros", "5.196 litros", "27.000 litros"],
    answer: 1,
    insight: "Comprar menos e usar mais: cada camiseta nova “custa” cerca de 2.700 litros.",
    litersSaved: 2700,
  },
];

export const WEEKLY_CHALLENGES = [
  {
    id: "meat-free",
    title: "Um almoço sem carne",
    description: "Troque uma porção de carne bovina por feijão, ovos ou legumes.",
    litersSaved: 1800,
  },
  {
    id: "coffee-cut",
    title: "Uma xícara a menos",
    description: "Pule um café extra no dia — ou compartilhe a cafeteira em vez de doses individuais.",
    litersSaved: 840,
  },
  {
    id: "ai-batch",
    title: "Agrupe os prompts",
    description: "Junte perguntas em um único comando em vez de disparar dezenas de chats curtos.",
    litersSaved: 1.2,
  },
  {
    id: "clothes",
    title: "Vista o que já tem",
    description: "Adie a compra de uma peça nesta semana. Um jeans evitado vale 5.196 litros.",
    litersSaved: 5196,
  },
];

export const TIPS = [
  {
    title: "Prefira proteínas vegetais algumas vezes na semana",
    description: "Substituir 1 kg de carne bovina por feijão economiza cerca de 11.000 litros.",
    litersSaved: 11000,
    category: "food",
  },
  {
    title: "Use a roupa até o fim da vida útil",
    description: "Estender o uso de um jeans por mais um ano dilui 5.196 litros em mais usos.",
    litersSaved: 5196,
    category: "clothing",
  },
  {
    title: "Agrupe tarefas de IA",
    description: "Menos idas e voltas ao modelo significa menos ciclos de resfriamento no data center.",
    litersSaved: 2,
    category: "digital",
  },
  {
    title: "Conserte vazamentos em casa",
    description: "Um torneira pingando desperdiça litros potáveis — água que já foi tratada.",
    litersSaved: 40,
    category: "home",
  },
];
